GFLAGS = -O2
.PHONY all

all: fscanf sscanf sscanf_mem

fscanf: fscanf.c
        gcc $(CFLAGS) -o $@ $<

sscanf: sscanf.c
        gcc $(CFLAGS) -o $@ $<
sscanf_mem: sscanf_mem.c
        gcc $(CFLAGS) -o $@ $<
atof: atof.c
        gcc $(CFLAGS) -o $@ $<
char: char.c
        gcc $(CFLAGS) -o $@ $<

